image: python:3.7-buster

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
cache:
  paths:
    - .cache/pip

stages:
  - test
  - build
  - deploy

test:36:
  image: python:3.6-buster
  stage: test
  artifacts:
    paths:
      - htmlcov/
  before_script:
    - apt-get update
    - apt-get install -y unixodbc-dev
    - pip install . .[mssql] pytest
  script:
    - pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'

test:37:
  image: python:3.7-buster
  stage: test
  artifacts:
    paths:
      - htmlcov/
  before_script:
    - apt-get update
    - apt-get install -y unixodbc-dev
    - pip install . .[mssql] pytest
  script:
    - pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'

test:38:
  image: python:3.8-buster
  stage: test
  artifacts:
    paths:
      - htmlcov/
  before_script:
    - apt-get update
    - apt-get install -y unixodbc-dev
    - pip install . .[mssql] pytest
  script:
    - pytest
  coverage: '/TOTAL.*\s+(\d+%)$/'

build:
  stage: build
  artifacts:
    paths:
      - dist/
  before_script:
    - apt-get update
    - apt-get install -y unixodbc-dev
    - pip install wheel
  script:
    - python setup.py sdist bdist_wheel

deploy:staging:
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install twine
  variables:
    TWINE_USERNAME: $TEST_PYPI_USERNAME
    TWINE_PASSWORD: $TEST_PYPI_PASSWORD
  script:
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
  only:
    - staging

deploy:pypi:
  stage: deploy
  dependencies:
    - build
  before_script:
    - pip install twine
  variables:
    TWINE_USERNAME: $LIVE_PYPI_USERNAME
    TWINE_PASSWORD: $LIVE_PYPI_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
    - ^v\d+\.\d+\.\d+$

